---

- hosts: all
  vars:
    user: ubuntu
  tasks:
    - name: Installing git  and zsh
      become: true
      apt: 
        name: "{{ item }}" 
        state: latest 
        update_cache: yes
      with_items:
        - git
        - zsh
        - git-core
    - name: Installing apache
      become: true
      apt: 
        name: apache2 
        state: latest 
        update_cache: yes
    - name: Configuring oh-my-zsh
      become: true
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh
        dest: /home/{{user}}/.oh-my-zsh
    - name: Setting up template to oh my zsh
      become: true
      copy: 
        src: /home/{{user}}/.oh-my-zsh/templates/zshrc.zsh-template
        dest: /home/{{user}}/.zshrc
    - name: Configuring default theme from Oh my zsh
      become: true
      replace:
        path: /home/{{user}}/.zshrc
        regexp: 'ZSH_THEME="robbyrussell"'
        replace: 'ZSH_THEME="kardan"'
    - name: Change default bash
      become: true
      user:
        force: true
        name: "{{user}}"
        shell: /bin/zsh
    - name: Instaling mysql with dependencies
      become: true
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items: 
        - mysql-server
        - python-mysqldb
    - name: Change server name
      become: true
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '#ServerName www.example.com'
        replace: 'ServerName localhost'
    - name: Adding PPA to php
      become: true
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/php'
        state: present
    - name: Installing apache2 dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - php-pear 
        - libapache2-mod-php7.0
        - apache2-utils
        - php-xml
        - php-mysql
        - php7.0-mbstring
        - php7.0            
        - php7.0-cli        
        - php7.0-dev        
        - php7.0-gmp        
        - php7.0-json       
        - php7.0-mysql      
        - php7.0-phpdbg     
        - php7.0-tidy       
        - php7.0-zip      
        - php7.0-bcmath     
        - php7.0-common     
        - php7.0-enchant    
        - php7.0-imap       
        - php7.0-ldap       
        - php7.0-odbc       
        - php7.0-pspell     
        - php7.0-soap       
        - php7.0-xml                        
        - php7.0-bz2        
        - php7.0-curl       
        - php7.0-fpm        
        - php7.0-interbase  
        - php7.0-mbstring   
        - php7.0-opcache    
        - php7.0-readline   
        - php7.0-sqlite3    
        - php7.0-xmlrpc                     
        - php7.0-cgi        
        - php7.0-dba        
        - php7.0-gd         
        - php7.0-intl       
        - php7.0-mcrypt     
        - php7.0-pgsql      
        - php7.0-recode     
        - php7.0-sybase     
        - php7.0-xsl 

    - name: Change apache root
      become: true
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'DocumentRoot /var/www/html'
        replace: 'DocumentRoot /home/{{user}}/www'
    - name: Set www directory user as a default root directory
      become: true
      blockinfile:
        path: /etc/apache2/sites-available/000-default.conf
        insertafter: 'DocumentRoot /home/{{user}}/www'
        content: |
          <Directory "/home/{{user}}/www">
            Options Indexes FollowSymLinks
            AllowOverride all
            Require all granted
          </Directory>
    - name: enabled mod_rewrite
      become: true
      apache2_module:
        name: rewrite
        state: present
    - name: Create user project one name ronaldo
      become: true
      mysql_user:
        name: ronaldo
        priv: '*.*:ALL'
        password: ronaldo123123
        state: present
    - name: Create projectronaldoone database
      become: true
      mysql_db:
        name: projectronaldoone
        state: present
        login_user: ronaldo
        login_password: ronaldo123123
    - name: Download composer
      become: true
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer
      tags: composer
    - name: install composer
      become: true
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer
      tags: composer
    - name: Rename composer.phar to composer
      become: true
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer
      tags: composer
    - name: Make composer executable
      become: true
      file: 
        path: /usr/local/bin/composer
        mode: a+x
        state: file
      tags: composer
    - name: Require drush via Composer globally.
      composer:
        command: require
        global_command: yes
        arguments: "drush/drush"
    - name: Creating a link for drush
      become: true
      file:
        src: "/home/{{user}}/.config/composer/vendor/bin/drush"
        dest: "/usr/local/bin/drush"
        state: link
    - name: Reload apache2
      become: true
      service:
        name: apache2
        state: reloaded
